# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thiago Sciotta
email: thiagog3@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Compartilhando minha visão de construção de produtos digitais amigáveis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sciotta.design" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/
twitter_username: falhamecanica
github_username:  thiagog3

plainwhite:
  name: Thiago Sciotta
  tagline: Developer. Designer.
  date_format: "%d/%m/%Y"
  analytics_id: UA-158278795-1
  disqus_shortname: thiagosciotta

  # generate social links in footer
  social_links:
    twitter: falhamecanica
    github:  thiagog3
    linkedIn: in/sciotta
    # rss: rss

# Build settings
markdown: kramdown
remote_theme: thelehhman/plainwhite-jekyll
show_excerpts: true
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
